sudo: required
language: python

notifications:
  slack: padmec:yzpcGXUkrIf1A11wvdBgn2d4

python:
  - "2.7"

services:
  - docker

before_install:
- docker build -t elliptic docker/elliptic/

install:
- pip install python-coveralls colorlog

script:
- docker run elliptic /bin/bash -c "cd ELLIPTIc; python setup.py test"

after_success:
# Fixing coverage paths:
# https://github.com/pytest-dev/pytest-cov/issues/146
- docker cp `docker ps -l -q`:/home/scientific/ELLIPTIc/.coverage .coverage.docker
- coverage combine
- coveralls
- docker tag elliptic padmec/elliptic:1.0
- if [ "$TRAVIS_BRANCH" == "master" ]; then
  docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  docker push padmec/elliptic:1.0;
  fi
- wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
- chmod +x send.sh
- ./send.sh success

after_failure:
- wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
- chmod +x send.sh
- ./send.sh failure
